[package]
name = "simple-icp"
version = "0.1.0"
edition = "2021"

[dependencies]
colorous = "1.0.14"
glob = "0.3.1"
nalgebra = "0.33.0"
pcd-rs = { version = "0.11.1", features = ["derive"] }
rayon = "1.10.0"
rerun = "0.17.0"
serde = "1.0.209"
serde_json = "1.0.128"
